### ISSUE TITLE
Changing the default branch of Zarr-Python

### ISSUE THREAD

**Issue by MSanKeys963** [zarr-developers/governance#15]
Considering the [PRs](https://github.com/zarr-developers/zarr-python/pulls/grlee77) opened by [@grlee77](https://github.com/grlee77) to add V3 in [Zarr-Python](https://github.com/zarr-developers/zarr-python), I and @joshmoore propose that we review and merge the PRs by [@grlee78](https://github.com/grlee77) into `main` and change the default branch to `v2-main` or something similar.

This will allow us to:

- Move towards the development of stable V3
- All the new PRs by the community and users will be opened into `main` which would have V3 features added by [@grlee77](https://github.com/grlee77). This would help us find any bugs/issues and fix them.

Thoughts?

Cc: @jakirkham @alimanfoo @rabernat @ryan-williams

**Comment by MSanKeys963** [comment]
Update: [@grlee78's](https://github.com/grlee77) [PR](https://github.com/zarr-developers/zarr-python/pull/898) has passed all the checks and is ready for reviewing and merging.

**Comment by joshmoore** [comment]
> change the default branch to `v2-main` or something similar.

I'd like to clarify that in mind this sentence is "change the _current_ default branch (i.e.`master`) to `v2-something`".

Basically, there are three calls for objections (and/or requests for alternatives):

1. Objections to renaming `master` to `main` on `zarr-python` per https://github.com/zarr-developers/community/issues/44?
2. Objections to creating separate "stable" and "dev" branches? (Naming to be worked out)
3. Objections to making the "dev" branch the default in order to drive the v3 work?

**Comment by joshmoore** [comment]
Feedback from today's call:
 - There's no real concern with getting https://github.com/zarr-developers/zarr-python/pull/898 merged.
 - The driving issue here is that the stability of v3 is a bit in question due to https://github.com/zarr-developers/zarr-specs/pull/134.
 - However, there is some concern about the overhead of maintaining two branches.
 - @jbms suggests the alternative of a [feature toggle](https://martinfowler.com/articles/feature-toggles.html) (e.g. by preventing the import of the v3 classes unless a variable is set)

Thoughts still welcome. 898 at least is unblocked, and a decision on this issue will only need to be made when the time for 2.11.2 comes.

**Comment by jakirkham** [comment]
Sorry for missing the call. Was out sick most of the week.

Sounds like the branch versioning issue is less pressing.

In case there is still a need for branch versioning, would suggest we consider an approach where the non-latest major version branch is broken out (`v2`) and `main` points to the latest major version.

**Comment by MSanKeys963** [comment]
Is it safe to close this issue?
