### ISSUE TITLE
Invitation to Zarr Implementation Council (z5)

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/governance#26]
_attn:_ @constantinpape

## Introduction

Changes to the Zarr specification impact all implementors. In order to manage
that burden, the Zarr project has formed an implementation council. Each
implementation community selects one person to sit on the council to help shape
changes to the Zarr spec.

## Rights & Responsibilities

The hope is that sitting on the council is itself a minimal additional burden.
Each decision to be made will be encapsulated as a "ZEP" (Zarr Enhancement
Process) which will need to be voted on. Each community can state that they
intend to actively implement ("YES") that they might eventually implement
("ABSTRAIN") or that they will never implement ("VETO").

Members of the Implementation Council will be added to the similarly named
team on GitHub which has privileges on the zarr-specs and zep repos.

## Next steps

First, if you would like to read more on the council and the process surrounding it,
please see the [Governance document](https://github.com/zarr-developers/governance/blob/74d6f3fcd98ee76c5807d0f8754a195a3ce18876/GOVERNANCE.md#implementation-council)
as well as the [ZEP](https://github.com/zarr-developers/governance/blob/1d2f3989896955c8bff8dc8d3d03f7580eaa474e/ZEP/instructions/zep0000.md) itself for more information.

Then, please use this issue to let the steering council know either:
 * that you are not interested or perhaps do not have the capacity at this time
 * or whom you will be assigning as your council representative.

If any help or discussion is needed, feel free to do so here or link to other
issues/threads as necessary.

Finally, we invite any implementation that has joined the Implementation
Council to also host their implementation's repositories in the zarr-developers
GitHub organization. This is not mandatory and has no impact on voting rights.
Most importantly, we would like to show the vibrancy of the Zarr community
and the strength that comes from a larger number of implementations.

Thanks to all of you!

**Comment by constantinpape** [comment]
I am happy to join the zarr implementation council as z5 representative.

A few comments from my side:
- I am currently pretty busy, so I won't have much time for this, but reviewing ZEPs will be fine. I don't have the capacity to very actively monitor the ZEP repository though, so I would be very thankful for active pings if review or input is required.
- Similarly, I will not myself have much time to further develop z5 in the midterm. Thus I will likely `Abstain` on many of the more advanced features -- but that should in no way keep us from adopting them, I am very excited to see adoption of advanced features like sharding in the zarr spec! (And as a sidenote, I am considering to deprecate the `z5` c++ backend in favor of xtensor-zarr, and just keeping `z5py` as alternative python implementation to `zarr-python`, both for legacy reasons and because I personally find its API, which is a more or less direct mirror of `h5py`, significantly clearer. However, there are still a few key features missing from xtensor-zarr, in particular n5 support, before I could make that switch.)
- Finally, I am planning on hiring an RSE in the mid-term, who might take on some of the z5 maintenance, in which case I might also delegate the representative role.
